apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
spec:
  type: ClusterIP
  ports:
    - name: pgsql
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: postgresql